# Generated by Django 3.2.5 on 2021-07-15 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('guest', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodgeNumber', models.PositiveIntegerField()),
                ('squareFeet', models.PositiveIntegerField()),
                ('numBedrooms', models.PositiveIntegerField()),
                ('numBathrooms', models.PositiveIntegerField()),
                ('operational', models.BooleanField()),
                ('available', models.BooleanField()),
                ('view', models.CharField(max_length=100)),
                ('pricePerNight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricePerWeek', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('origin', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inStock', models.BooleanField()),
                ('quantity', models.PositiveIntegerField()),
                ('bottleSize', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOnly', models.BooleanField()),
                ('numNights', models.PositiveIntegerField(null=True)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chateau_du_vin_app.customer')),
                ('lodge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chateau_du_vin_app.lodge')),
            ],
        ),
    ]
